services:
  # --- ENGINE DATABASE (MySQL Server) ---
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-caddy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- ENGINE UTAMA APLIKASI (BookStack Wiki) ---
  bookstack:
    image: solidnerd/bookstack:${BOOKSTACK_VERSION}
    container_name: bookstack
    depends_on:
      mysql:
        # Proteksi: Memastikan database sehat sebelum aplikasi up
        condition: service_healthy
    networks:
      - net-caddy
    environment:
      # Koneksi Database Internal
      - DB_HOST=mysql:3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      # Konfigurasi Inti Web Host (Dinamis)
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - APACHE_SERVER_NAME=${SERVER_DOMAIN}
      - APP_THEME=custom
      - TZ=${TZ}

      # Solusi Fix Localhost / Mixed Content Assets TLS
      - APP_PROXIES=*

      # Integrasi SSO OpenID Connect (OIDC) Keycloak
      - AUTH_METHOD=oidc
      - OIDC_NAME="Login Agson"
      - OIDC_DISPLAY_NAME_CLAIMS=name
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_ISSUER=${OIDC_ISSUER}
      - OIDC_ISSUER_DISCOVER=true
      - OIDC_END_SESSION_ENDPOINT=${OIDC_LOGOUT_ENDPOINT}
      - OIDC_EMAIL_CLAIMS=email
      - ALLOW_PASSWORD_LOGIN=true

    ports:
      - "8080:8080"
    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/storage/uploads
      # Folder kustomisasi hacks / themes functions Anda
      - ./themes:/var/www/bookstack/themes
    restart: unless-stopped

# --- DEKLARASI DATA VOLUME PERSISTEN ---
volumes:
  mysql-data:
  uploads:
  storage-uploads:

# --- DEKLARASI JARINGAN REVERSE PROXY ---
networks:
  net-caddy:
    # Menggunakan jaringan eksternal terintegrasi Caddy SSL
    external: true
